"""
generate_videos.py
For each unsent sheet row that has a matching Loom recording:
  1. Download Riz's edited Loom MP4 (GraphQL API, no MCP needed)
  2. Screenshot the restaurant's website (Playwright)
  3. Composite: website as full-screen background, Riz as PiP overlay (FFmpeg)
  4. Upload final .mp4 to Google Drive → get shareable link
  5. Write drive_video_url + drive_thumbnail_url back to the sheet

Usage:
    python generate_videos.py                  # process all unprocessed rows
    python generate_videos.py --limit 5        # cap at 5 restaurants
    python generate_videos.py --dry-run        # match + download only, no FFmpeg/Drive
    python generate_videos.py --restaurant "Dishoom"  # single restaurant by name

Requirements (.env):
    LOOM_COOKIE              connect.sid=s%3A... (from browser DevTools → Application → Cookies)
    GOOGLE_SHEETS_KEY_FILE   service account JSON
    GOOGLE_SHEETS_ID         spreadsheet ID
    GOOGLE_DRIVE_FOLDER_ID   Drive folder to upload videos into

Sheet columns added by this script:
    loom_video_id     Loom video ID matched to this restaurant
    drive_video_url   Google Drive shareable link to composited MP4
    drive_thumbnail_url  Direct link to Drive thumbnail image

FFmpeg required: brew install ffmpeg
"""

import argparse
import logging
import os
import subprocess
import tempfile
import time
from pathlib import Path
from datetime import datetime, timezone

import requests
import gspread
from google.oauth2.service_account import Credentials as SACredentials
from googleapiclient.discovery import build
from googleapiclient.http import MediaFileUpload
from playwright.sync_api import sync_playwright, TimeoutError as PWTimeout
from dotenv import load_dotenv

load_dotenv()

# ── Config ────────────────────────────────────────────────────────────────────

CONTACTS_TAB = "contacts"
CRAWL_DELAY = 1.5

# PiP layout: Riz face cam in bottom-left, 25% of video width
PIP_SCALE = 0.25
PIP_MARGIN = 20        # px from edges
OUTPUT_WIDTH = 1280
OUTPUT_HEIGHT = 720

CHROMA_KEY_COLOR = "0x00FF00"   # green screen
CHROMA_KEY_SIMILARITY = 0.45
CHROMA_KEY_BLEND = 0.05

# Audio splice: ElevenLabs "Hey [name]" MP3 + template "I'm Riz..." audio
# "Hey" is now baked into the name MP3 (generate_audio.py prepends it) — no separate hey.mp3
# TEMPLATE_NAME_END = where "I'm Riz..." starts in the template audio
TEMPLATE_NAME_END  = 0       # seconds into template where "I'm Riz..." begins (v3 recording starts directly with "I'm Riz")

# Template recording — downloaded from Drive at runtime (same as name audio)
TEMPLATE_DRIVE_FILE_ID = "1JguWdRWENmRsmXj2TqIdkj5f0zNjfxKV"

GSHEETS_SCOPES = [
    "https://www.googleapis.com/auth/spreadsheets",
    "https://www.googleapis.com/auth/drive",
]
GDRIVE_SCOPES = ["https://www.googleapis.com/auth/drive"]

LOOM_GRAPHQL_URL = "https://www.loom.com/graphql"

# ── Logging ───────────────────────────────────────────────────────────────────

logging.basicConfig(
    level=logging.INFO,
    format="%(asctime)s  %(levelname)-8s  %(message)s",
    datefmt="%H:%M:%S",
)
log = logging.getLogger(__name__)

# ── Loom GraphQL client (pure requests, no MCP) ───────────────────────────────

class LoomClient:
    """Minimal Loom GraphQL client. Replicates karbassi/mcp-loom in plain requests.

    Auth priority:
      1. credentials/loom_auth.json (Playwright storage state — all loom.com cookies)
         Generated by: python save_loom_cookies.py
      2. LOOM_COOKIE env var (single connect.sid string — fallback only)
    """

    # Default auth file path (relative to project root)
    AUTH_FILE = Path("credentials/loom_auth.json")

    def __init__(self, cookie: str = ""):
        import json
        from urllib.parse import unquote

        # Prefer the full storage state (all cookies) over a single connect.sid
        auth_file = Path(os.environ.get("LOOM_AUTH_FILE", str(self.AUTH_FILE)))
        if auth_file.exists():
            state = json.loads(auth_file.read_text())
            loom_cookies = [c for c in state["cookies"] if "loom.com" in c.get("domain", "")]
            has_session = any(c["name"] == "connect.sid" for c in loom_cookies)
            if has_session:
                cookie_str = "; ".join(f"{c['name']}={c['value']}" for c in loom_cookies)
                log.debug("Loom auth: loaded %d cookies from %s", len(loom_cookies), auth_file)
            else:
                log.warning("Auth file %s has no connect.sid — falling back to LOOM_COOKIE", auth_file)
                auth_file = Path("__nonexistent__")  # force fallback below
        elif cookie:
            # Send the cookie exactly as stored — do NOT URL-decode.
            # Chrome stores and sends connect.sid as s%3A... (not s:...)
            # Loom's server expects the raw percent-encoded form.
            cookie_str = cookie
            if not cookie_str.startswith("connect.sid="):
                cookie_str = f"connect.sid={cookie_str}"
            log.debug("Loom auth: using LOOM_COOKIE env var (single cookie)")
        else:
            raise ValueError(
                "Loom auth not configured. Run: python save_loom_cookies.py\n"
                "Or set LOOM_COOKIE in .env as a fallback."
            )

        self.session = requests.Session()
        self.session.headers.update({
            "content-type": "application/json",
            "apollographql-client-name": "web",
            "x-loom-request-source": "loom_web",
            "origin": "https://www.loom.com",
            "referer": "https://www.loom.com/",
            "cookie": cookie_str,
        })

    def graphql(self, operation: str, query: str, variables: dict = None) -> dict:
        r = self.session.post(
            LOOM_GRAPHQL_URL,
            json={"operationName": operation, "query": query, "variables": variables or {}},
            timeout=30,
        )
        if r.status_code == 401:
            raise RuntimeError("Loom session expired — refresh LOOM_COOKIE in .env")
        r.raise_for_status()
        body = r.json()
        if body.get("errors"):
            msgs = [e.get("message", "?") for e in body["errors"]]
            raise RuntimeError(f"Loom GraphQL error: {'; '.join(msgs)}")
        return body["data"]

    def whoami(self) -> dict:
        """Multi-query auth diagnostic — tests several endpoints to isolate the problem."""
        tests = [
            ("getUserWatchLaterListCount", {
                "operationName": "GetUserWatchLaterListCount",
                "query": "query GetUserWatchLaterListCount { getUserWatchLaterListCount { ... on WatchLaterListVideoCount { count } __typename } }",
                "variables": {},
            }),
            ("getMySpaceMemberships", {
                "operationName": "GetMySpaceMemberships",
                "query": "query GetMySpaceMemberships($first: Int!, $after: String) { result: getMySpaceMemberships { __typename ... on GetMySpaceMembershipsPayload { memberships(first: $first, after: $after) { edges { node { id } } } } } }",
                "variables": {"first": 5, "after": None},
            }),
            ("getLooms (no filters)", {
                "operationName": "GetLoomsForLibrary",
                "query": """query GetLoomsForLibrary($limit: Int!, $source: LoomsSource!, $sortType: LoomsSortType!, $sortOrder: LoomsSortOrder!) {
                  getLooms {
                    __typename
                    ... on GetLoomsPayload {
                      videos(first: $limit, source: $source, sortType: $sortType, sortOrder: $sortOrder) {
                        edges { node { id name } }
                      }
                    }
                  }
                }""",
                "variables": {"source": "MINE", "sortType": "RECENT", "sortOrder": "DESC", "limit": 5},
            }),
        ]
        # Print what cookie we're actually sending
        cookie_sent = self.session.headers.get("cookie", "")
        print(f"Cookie being sent: {cookie_sent[:60]}...")
        print(f"Cookie length: {len(cookie_sent)} chars\n")

        results = {}
        for name, payload in tests:
            r = self.session.post(LOOM_GRAPHQL_URL, json=payload, timeout=30)
            print(f"[{name}] HTTP {r.status_code}: {r.text[:300]}")
            results[name] = r.json()
        return results

    def list_all_videos(self) -> list[dict]:
        """Pages through all videos in Riz's library."""
        videos = []
        cursor = None
        while True:
            data = self.graphql(
                "GetLoomsForLibrary",
                """query GetLoomsForLibrary($limit: Int!, $cursor: String, $source: LoomsSource!, $sortType: LoomsSortType!, $sortOrder: LoomsSortOrder!, $filters: [[LoomsCollectionFilter!]!]) {
                  getLooms {
                    __typename
                    ... on GetLoomsPayload {
                      videos(first: $limit, after: $cursor, source: $source, sortType: $sortType, sortOrder: $sortOrder, filters: $filters) {
                        edges { cursor node { id name visibility } }
                        pageInfo { endCursor hasNextPage }
                      }
                    }
                  }
                }""",
                {
                    "source": "MINE",
                    "sortType": "RECENT",
                    "sortOrder": "DESC",
                    "filters": [[{"type": "CREATED_BY_ME"}], [{"type": "NOT_IN_FOLDER"}]],
                    "limit": 50,
                    "cursor": cursor,
                },
            )
            looms = data["getLooms"]
            if "videos" not in looms:
                typename = looms.get("__typename", "unknown")
                raise RuntimeError(f"Loom auth failed (type={typename}). Check LOOM_COOKIE in .env")
            page = looms["videos"]
            videos.extend(e["node"] for e in page["edges"])
            if not page["pageInfo"]["hasNextPage"]:
                break
            cursor = page["pageInfo"]["endCursor"]
        return videos

    def get_download_url(self, video_id: str) -> str | None:
        data = self.graphql(
            "GetVideoTranscodedUrl",
            """query GetVideoTranscodedUrl($videoId: ID!, $forceOriginal: Boolean) {
              getVideoTranscodedUrl(videoId: $videoId, forceOriginal: $forceOriginal) {
                ... on VideoSource { url }
              }
            }""",
            {"videoId": video_id, "forceOriginal": False},
        )
        return (data.get("getVideoTranscodedUrl") or {}).get("url")

    def download_mp4(self, video_id: str, dest_path: Path) -> bool:
        """Downloads the MP4 for a video ID to dest_path. Returns True on success."""
        url = self.get_download_url(video_id)
        if not url:
            log.warning("No download URL for video %s", video_id)
            return False
        log.info("  Downloading Loom MP4 ...")
        r = self.session.get(url, stream=True, timeout=120)
        r.raise_for_status()
        dest_path.write_bytes(r.content)
        log.info("  Downloaded → %s (%.1f MB)", dest_path.name, dest_path.stat().st_size / 1e6)
        return True


def match_loom_recording(videos: list[dict], restaurant_name: str) -> dict | None:
    """
    Finds the Loom recording whose name best matches the restaurant name.
    Tries exact match first, then case-insensitive, then substring.
    """
    name_lower = restaurant_name.lower().strip()
    # Exact
    for v in videos:
        if v["name"].strip() == restaurant_name:
            return v
    # Case-insensitive exact
    for v in videos:
        if v["name"].lower().strip() == name_lower:
            return v
    # Substring (restaurant name appears in video name or vice versa)
    for v in videos:
        v_lower = v["name"].lower().strip()
        if name_lower in v_lower or v_lower in name_lower:
            return v
    return None


# ── Cookie banner dismissal ───────────────────────────────────────────────────

def dismiss_cookie_banner(page) -> None:
    """
    Tries to dismiss cookie consent popups before screenshotting.
    Attempts common selectors + button text patterns. Silent if nothing found.
    """
    # Common framework-specific selectors (try these first — fastest)
    specific_selectors = [
        "#onetrust-accept-btn-handler",                          # OneTrust
        "#CybotCookiebotDialogBodyLevelButtonLevelOptinAllowAll", # Cookiebot
        ".cookie-information-template-wrapper button.accept",    # CookieInformation (screenshot)
        "[data-testid='cookie-policy-dialog-accept-button']",    # various
        "#cookie-accept",
        ".cc-accept",
        ".cc-btn.cc-allow",
        "[aria-label='Accept cookies']",
        "[aria-label='Accept all cookies']",
    ]

    # Common button text patterns (case-insensitive)
    button_texts = [
        "Accept All", "Accept all", "ACCEPT ALL",
        "Allow All", "Allow all", "ALLOW ALL",
        "Accept", "ACCEPT",
        "Agree", "I Agree", "I agree",
        "OK", "Ok", "Got it",
        "Decline All", "Decline all", "DECLINE ALL",  # declining is fine too — just closes it
    ]

    for selector in specific_selectors:
        try:
            btn = page.locator(selector).first
            if btn.is_visible(timeout=800):
                btn.click(timeout=800)
                page.wait_for_timeout(500)
                log.debug("  Dismissed cookie banner via selector: %s", selector)
                return
        except Exception:
            continue

    for text in button_texts:
        try:
            btn = page.get_by_role("button", name=text, exact=False).first
            if btn.is_visible(timeout=800):
                btn.click(timeout=800)
                page.wait_for_timeout(500)
                log.debug("  Dismissed cookie banner via text: %s", text)
                return
        except Exception:
            continue


# ── Website screenshot ────────────────────────────────────────────────────────

def screenshot_website(url: str, dest_path: Path, timeout: int = 30000) -> bool:
    """
    Takes a screenshot of the restaurant website using Playwright + stealth mode.
    Stealth mode bypasses basic bot detection (Cloudflare JS challenge, etc.).
    Returns True on success.
    """
    if not url:
        log.warning("No website URL — cannot screenshot")
        return False
    try:
        with sync_playwright() as pw:
            browser = pw.chromium.launch(headless=True)
            context = browser.new_context(
                viewport={"width": OUTPUT_WIDTH, "height": OUTPUT_HEIGHT},
                user_agent=(
                    "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) "
                    "AppleWebKit/537.36 (KHTML, like Gecko) "
                    "Chrome/124.0.0.0 Safari/537.36"
                ),
            )
            # Apply stealth patches to avoid bot detection
            try:
                from playwright_stealth import stealth_sync
                page = context.new_page()
                stealth_sync(page)
            except ImportError:
                page = context.new_page()

            page.goto(url, wait_until="networkidle", timeout=timeout)
            dismiss_cookie_banner(page)
            time.sleep(1.5)  # allow lazy-loaded content
            page.screenshot(path=str(dest_path), clip={
                "x": 0, "y": 0, "width": OUTPUT_WIDTH, "height": OUTPUT_HEIGHT
            })
            browser.close()
        log.info("  Screenshot saved → %s", dest_path.name)
        return True
    except PWTimeout:
        log.warning("  Screenshot timed out for %s", url)
    except Exception as exc:
        log.warning("  Screenshot failed for %s: %s", url, exc)
    return False


# ── Audio splice ─────────────────────────────────────────────────────────────

def splice_name_audio(template_mp4: Path, name_mp3: Path, output_mp4: Path, riz_audio: Path | None = None) -> bool:
    """
    Builds audio from two sources:
      [0:a] name_mp3              → "Hey [Restaurant Name]"  (ElevenLabs, single utterance)
      [1:a] riz_audio (or template) → "I'm Riz..." (from TEMPLATE_NAME_END onwards)

    riz_audio: separate audio file for the "I'm Riz..." segment (Drive recording).
               If None, falls back to using template_mp4 audio (legacy behaviour).
    Video track is copied unchanged from template_mp4 (Loom headshot).
    """
    if riz_audio is not None:
        # Three inputs: name_mp3, template_mp4 (video only), riz_audio (audio only)
        # loudnorm on both streams so ElevenLabs TTS and Drive recording match in volume
        filter_complex = (
            f"[0:a]loudnorm[part1];"
            f"[2:a]atrim={TEMPLATE_NAME_END},asetpts=PTS-STARTPTS,loudnorm[part2];"
            f"[part1][part2]concat=n=2:v=0:a=1[out]"
        )
        cmd = [
            "ffmpeg", "-y",
            "-i", str(name_mp3),       # input 0: ElevenLabs "Hey [name]"
            "-i", str(template_mp4),   # input 1: Loom headshot (video only)
            "-i", str(riz_audio),      # input 2: Drive recording ("I'm Riz..." audio)
            "-filter_complex", filter_complex,
            "-map", "1:v",             # video from Loom template
            "-map", "[out]",           # spliced audio
            "-c:v", "copy",
            "-c:a", "aac",
            str(output_mp4),
        ]
    else:
        # Legacy: template provides both video and "I'm Riz..." audio
        filter_complex = (
            f"[0:a]asetpts=PTS-STARTPTS[part1];"
            f"[1:a]atrim={TEMPLATE_NAME_END},asetpts=PTS-STARTPTS,afftdn=nf=-20[part2];"
            f"[part1][part2]concat=n=2:v=0:a=1[out]"
        )
        cmd = [
            "ffmpeg", "-y",
            "-i", str(name_mp3),       # input 0: ElevenLabs "Hey [name]"
            "-i", str(template_mp4),   # input 1: template (video + "I'm Riz..." audio)
            "-filter_complex", filter_complex,
            "-map", "1:v",
            "-map", "[out]",
            "-c:v", "copy",
            "-c:a", "aac",
            str(output_mp4),
        ]

    log.info("  Splicing name audio into template ...")
    result = subprocess.run(cmd, capture_output=True, text=True, timeout=120)
    if result.returncode != 0:
        log.error("  FFmpeg splice failed:\n%s", result.stderr[-2000:])
        return False
    log.info("  Spliced → %s", output_mp4.name)
    return True


# ── FFmpeg composite ──────────────────────────────────────────────────────────

def composite_video(
    loom_mp4: Path,
    screenshot_png: Path,
    output_mp4: Path,
) -> bool:
    """
    Chroma-keys the green screen from the Loom MP4 and composites Riz's circular
    face cam onto the restaurant screenshot.

    Layout:
      - input 0: screenshot_png  → full-screen background (looped static image)
      - input 1: loom_mp4        → Riz's personalised recording (green keyed out, audio kept)

    FFmpeg filter:
      [0:v] scale to OUTPUT_WIDTH x OUTPUT_HEIGHT                     → [bg]
      [1:v] colorkey removes green → scale to PIP_SCALE width         → [pip]
      [bg][pip] overlay bottom-left with PIP_MARGIN                   → [out]
      audio from Loom, stop when it ends (-shortest)
    """
    pip_width = int(OUTPUT_WIDTH * PIP_SCALE)

    filter_complex = (
        f"[0:v]scale={OUTPUT_WIDTH}:{OUTPUT_HEIGHT},setsar=1[bg];"
        f"[1:v]colorkey={CHROMA_KEY_COLOR}:{CHROMA_KEY_SIMILARITY}:{CHROMA_KEY_BLEND},"
        f"scale={pip_width}:-2[pip];"
        f"[bg][pip]overlay=x={PIP_MARGIN}:y=main_h-overlay_h-{PIP_MARGIN}:format=auto[out]"
    )

    cmd = [
        "ffmpeg", "-y",
        "-loop", "1", "-i", str(screenshot_png),   # input 0: background (looped static)
        "-i", str(loom_mp4),                        # input 1: Loom video + audio
        "-filter_complex", filter_complex,
        "-map", "[out]",
        "-map", "1:a?",                             # audio from Loom
        "-c:v", "libx264",
        "-preset", "fast",
        "-crf", "23",
        "-c:a", "aac",
        "-shortest",                                # stop when Loom ends
        str(output_mp4),
    ]

    log.info("  Running FFmpeg composite (chroma key + face cam PiP) ...")
    result = subprocess.run(cmd, capture_output=True, text=True, timeout=300)
    if result.returncode != 0:
        log.error("  FFmpeg failed:\n%s", result.stderr[-2000:])
        return False
    log.info("  Composite video → %s (%.1f MB)", output_mp4.name, output_mp4.stat().st_size / 1e6)
    return True


# ── Google Drive upload ───────────────────────────────────────────────────────

def get_drive_service():
    """
    Uses OAuth credentials (same as Gmail) — service accounts have no Drive quota.
    Reuses credentials/gmail_token.json; adds drive scope if not already present.
    On first run with drive scope, browser opens for re-auth.
    """
    from google.oauth2.credentials import Credentials as OAuthCredentials
    from google_auth_oauthlib.flow import InstalledAppFlow
    from google.auth.transport.requests import Request

    DRIVE_SCOPES = [
        "https://www.googleapis.com/auth/gmail.send",
        "https://www.googleapis.com/auth/drive",
    ]
    token_file = os.environ.get("GMAIL_TOKEN_FILE", "credentials/gmail_token.json")
    creds_file = os.environ.get("GMAIL_CREDENTIALS_FILE", "credentials/oath_client.json")

    creds = None
    if Path(token_file).exists():
        creds = OAuthCredentials.from_authorized_user_file(token_file, DRIVE_SCOPES)

    if not creds or not creds.valid:
        if creds and creds.expired and creds.refresh_token:
            creds.refresh(Request())
        else:
            flow = InstalledAppFlow.from_client_secrets_file(creds_file, DRIVE_SCOPES)
            creds = flow.run_local_server(port=0)
        Path(token_file).write_text(creds.to_json())

    return build("drive", "v3", credentials=creds)


def add_play_button(screenshot_png: Path) -> Path:
    """
    Composites a semi-transparent play button circle onto the centre of the thumbnail.
    Returns path to the new PNG (saved alongside the original with _play suffix).
    Falls back to original if Pillow is not installed.
    """
    try:
        from PIL import Image, ImageDraw
    except ImportError:
        log.warning("Pillow not installed — skipping play button (pip install Pillow)")
        return screenshot_png

    img = Image.open(screenshot_png).convert("RGBA")
    w, h = img.size

    overlay = Image.new("RGBA", img.size, (0, 0, 0, 0))
    draw = ImageDraw.Draw(overlay)

    # Circle: semi-transparent dark background
    radius = min(w, h) // 8
    cx, cy = w // 2, h // 2
    draw.ellipse(
        [cx - radius, cy - radius, cx + radius, cy + radius],
        fill=(0, 0, 0, 160),
    )

    # Triangle: white play icon offset slightly right of centre
    offset = radius // 6
    tri_size = radius // 2
    draw.polygon(
        [
            (cx - tri_size + offset, cy - tri_size),
            (cx - tri_size + offset, cy + tri_size),
            (cx + tri_size + offset, cy),
        ],
        fill=(255, 255, 255, 230),
    )

    result = Image.alpha_composite(img, overlay).convert("RGB")
    out_path = screenshot_png.with_stem(screenshot_png.stem + "_play")
    result.save(out_path)
    return out_path


def upload_to_drive(mp4_path: Path, screenshot_png: Path, restaurant_name: str, folder_id: str) -> tuple[str, str]:
    """
    Uploads MP4 + screenshot PNG to Google Drive folder.
    Returns (video_url, thumbnail_url).

    thumbnail_url uses lh3.googleusercontent.com/d/{id} — this is Google's CDN URL
    for publicly shared images, which loads correctly in email clients without auth.
    Drive's /thumbnail endpoint requires Google auth and breaks in emails.
    """
    service = get_drive_service()

    def upload_file(path: Path, mimetype: str, name: str) -> str:
        """Uploads a file, makes it public, returns file ID."""
        media = MediaFileUpload(str(path), mimetype=mimetype, resumable=True)
        file = service.files().create(
            body={"name": name, "parents": [folder_id]},
            media_body=media,
            fields="id",
        ).execute()
        fid = file["id"]
        service.permissions().create(
            fileId=fid,
            body={"type": "anyone", "role": "reader"},
        ).execute()
        return fid

    log.info("  Uploading video to Google Drive ...")
    video_id = upload_file(mp4_path, "video/mp4", f"{restaurant_name}.mp4")

    log.info("  Uploading thumbnail to Google Drive ...")
    thumb_with_play = add_play_button(screenshot_png)
    thumb_id = upload_file(thumb_with_play, "image/png", f"{restaurant_name}_thumb.png")

    video_url = f"https://drive.google.com/file/d/{video_id}/view?usp=sharing"
    # lh3.googleusercontent.com serves public Drive images directly — works in emails
    thumbnail_url = f"https://lh3.googleusercontent.com/d/{thumb_id}"

    log.info("  Uploaded → %s", video_url)
    return video_url, thumbnail_url


# ── Google Sheets ─────────────────────────────────────────────────────────────

def get_sheet_client():
    key_file = os.environ["GOOGLE_SHEETS_KEY_FILE"]
    creds = SACredentials.from_service_account_file(key_file, scopes=GSHEETS_SCOPES)
    return gspread.authorize(creds)


def load_contacts(sheet_id: str) -> tuple[gspread.Worksheet, list[str], list[dict]]:
    client = get_sheet_client()
    sheet = client.open_by_key(sheet_id)
    ws = sheet.worksheet(CONTACTS_TAB)
    all_rows = ws.get_all_values()
    if not all_rows:
        return ws, [], []
    headers = all_rows[0]
    rows = [dict(zip(headers, row)) for row in all_rows[1:]]
    return ws, headers, rows


def ensure_columns(ws: gspread.Worksheet, headers: list[str]) -> list[str]:
    """Adds drive_video_url, drive_thumbnail_url columns if missing."""
    needed = ["drive_video_url", "drive_thumbnail_url"]
    new_cols = [col for col in needed if col not in headers]
    if not new_cols:
        return headers
    # Expand the sheet grid first to fit new columns
    new_total_cols = len(headers) + len(new_cols)
    ws.resize(rows=ws.row_count, cols=new_total_cols)
    time.sleep(0.5)
    for col in new_cols:
        headers.append(col)
        ws.update_cell(1, len(headers), col)
        log.info("Added column: %s", col)
    time.sleep(1)
    return headers


def write_video_urls(
    ws: gspread.Worksheet,
    headers: list[str],
    row_index_1based: int,
    drive_video_url: str,
    drive_thumbnail_url: str,
):
    sheet_row = row_index_1based + 1  # +1 for header
    col_video = headers.index("drive_video_url") + 1
    col_thumb = headers.index("drive_thumbnail_url") + 1

    ws.update_cell(sheet_row, col_video, drive_video_url)
    ws.update_cell(sheet_row, col_thumb, drive_thumbnail_url)
    log.info("  ✓ Sheet updated (row %d)", sheet_row)


# ── Core pipeline ─────────────────────────────────────────────────────────────

def run(limit: int, dry_run: bool, only_restaurant: str | None):
    sheet_id = os.environ["GOOGLE_SHEETS_ID"]
    drive_folder_id = os.environ["GOOGLE_DRIVE_FOLDER_ID"]
    loom_cookie = os.environ["LOOM_COOKIE"]

    # Load sheet
    log.info("Loading contacts sheet ...")
    ws, headers, rows = load_contacts(sheet_id)
    if not rows:
        log.info("No rows in sheet.")
        return
    headers = ensure_columns(ws, headers)

    # Load Loom library — template video (headshot) still comes from Loom
    log.info("Fetching Loom video library ...")
    loom = LoomClient(loom_cookie)
    loom_videos = loom.list_all_videos()
    log.info("Found %d Loom recordings", len(loom_videos))

    # Find the template video (named "ADVNC" in Loom)
    template_video = match_loom_recording(loom_videos, "ADVNC")
    if not template_video:
        log.error("Template Loom video 'ADVNC' not found — upload recording_template_v2.mp4 to Loom named 'ADVNC'")
        return
    log.info("Template video: '%s' (id=%s)", template_video["name"], template_video["id"])

    # Filter rows: needs audio_verified=TRUE, no drive_video_url yet, has website + email
    pending = []
    for i, row in enumerate(rows):
        if only_restaurant and row.get("restaurant_name", "").lower() != only_restaurant.lower():
            continue
        if row.get("drive_video_url", "").strip():
            log.debug("Row %d (%s) — already processed, skipping", i + 2, row.get("restaurant_name"))
            continue
        if row.get("audio_verified", "").strip().upper() != "TRUE":
            log.debug("Row %d (%s) — audio not verified yet (run generate_audio.py first)", i + 2, row.get("restaurant_name"))
            continue
        if not row.get("website_url", "").strip():
            log.debug("Row %d (%s) — no website, skipping", i + 2, row.get("restaurant_name"))
            continue
        if not row.get("email", "").strip():
            log.debug("Row %d (%s) — no email address, skipping", i + 2, row.get("restaurant_name"))
            continue
        pending.append((i, row))

    log.info("%d rows to process (limit=%d)", len(pending), limit)

    processed = 0
    screenshot_failed = []      # rows that failed screenshot — retried at end with 60s timeout
    template_mp4_cached = None  # Loom headshot video — downloaded once, reused
    riz_audio_cached = None     # Drive recording audio — downloaded once, reused

    with tempfile.TemporaryDirectory() as tmpdir:
        tmp = Path(tmpdir)

        for i, row in pending:
            if processed >= limit:
                log.info("Limit of %d reached.", limit)
                break

            restaurant_name = row.get("restaurant_name", "").strip()
            website_url = row.get("website_url", "").strip()
            drive_audio_url = row.get("drive_audio_url", "").strip()

            log.info("[%d/%d] %s", processed + 1, min(limit, len(pending)), restaurant_name)

            if dry_run:
                log.info("  [dry-run] Would splice audio, composite, and upload")
                processed += 1
                continue

            # Step 1 — Download template (once, reused for all restaurants)
            if template_mp4_cached is None:
                # Loom template — headshot video
                template_mp4_cached = tmp / "template.mp4"
                if not loom.download_mp4(template_video["id"], template_mp4_cached):
                    log.error("  Template download failed — aborting")
                    return
                # Drive recording — "I'm Riz..." audio substitute
                log.info("  Downloading Riz audio from Drive ...")
                drive_svc = get_drive_service()
                riz_audio_cached = tmp / "riz_audio.mp4"
                riz_bytes = drive_svc.files().get_media(fileId=TEMPLATE_DRIVE_FILE_ID).execute()
                riz_audio_cached.write_bytes(riz_bytes)
                log.info("  Riz audio downloaded (%d MB)", len(riz_bytes) // 1_000_000)

            template_mp4 = template_mp4_cached

            # Step 2 — Download ElevenLabs name audio from Drive
            name_mp3 = tmp / f"{restaurant_name.replace(' ', '_')}_name.mp3"
            log.info("  Downloading name audio from Drive ...")
            # Extract file ID from drive_audio_url
            import re as _re
            m = _re.search(r"/d/([^/]+)/", drive_audio_url)
            if not m:
                log.warning("  Could not parse Drive file ID from audio URL — skipping")
                continue
            audio_file_id = m.group(1)
            drive_svc = get_drive_service()
            audio_bytes = drive_svc.files().get_media(fileId=audio_file_id).execute()
            name_mp3.write_bytes(audio_bytes)
            log.info("  Name audio downloaded → %s", name_mp3.name)

            # Step 3 — Splice name audio into template
            spliced_mp4 = tmp / f"{restaurant_name.replace(' ', '_')}_spliced.mp4"
            if not splice_name_audio(template_mp4, name_mp3, spliced_mp4, riz_audio=riz_audio_cached):
                log.warning("  Audio splice failed — skipping")
                continue

            # Step 4 — Screenshot restaurant website
            screenshot = tmp / f"{restaurant_name.replace(' ', '_')}_bg.png"
            if not screenshot_website(website_url, screenshot):
                log.warning("  Screenshot failed — queued for retry with 60s timeout")
                screenshot_failed.append((i, row, spliced_mp4))
                continue

            # Step 5 — FFmpeg composite (chroma key + face cam overlay)
            output_mp4 = tmp / f"{restaurant_name.replace(' ', '_')}_final.mp4"
            if not composite_video(spliced_mp4, screenshot, output_mp4):
                log.warning("  FFmpeg composite failed — skipping")
                continue

            # Step 6 — Upload to Google Drive
            try:
                drive_video_url, drive_thumbnail_url = upload_to_drive(
                    output_mp4, screenshot, restaurant_name, drive_folder_id
                )
            except Exception as exc:
                log.error("  Drive upload failed: %s", exc)
                continue

            # Step 7 — Write back to sheet
            write_video_urls(ws, headers, i + 1, drive_video_url, drive_thumbnail_url)
            processed += 1

            # Clean up per-restaurant temp files (keep template_mp4_cached)
            name_mp3.unlink(missing_ok=True)
            spliced_mp4.unlink(missing_ok=True)
            screenshot.unlink(missing_ok=True)
            output_mp4.unlink(missing_ok=True)

            time.sleep(CRAWL_DELAY)

        # ── Retry pass: screenshot failures with 60s timeout ──────────────────
        if screenshot_failed:
            log.info("Retrying %d screenshot failure(s) with 60s timeout ...", len(screenshot_failed))
            for i, row, spliced_mp4 in screenshot_failed:
                if processed >= limit:
                    log.info("Limit of %d reached — skipping remaining retries.", limit)
                    break
                restaurant_name = row.get("restaurant_name", "").strip()
                website_url = row.get("website_url", "").strip()
                log.info("  [retry] %s", restaurant_name)

                screenshot = tmp / f"{restaurant_name.replace(' ', '_')}_bg.png"
                if not screenshot_website(website_url, screenshot, timeout=60000):
                    # Website timed out twice — fall back to Instagram profile
                    instagram_url = row.get("instagram_url", "").strip()
                    if instagram_url:
                        log.info("  [retry] Website still failed — trying Instagram: %s", instagram_url)
                        if not screenshot_website(instagram_url, screenshot, timeout=30000):
                            log.warning("  [retry] Instagram screenshot also failed — skipping %s", restaurant_name)
                            continue
                    else:
                        log.warning("  [retry] Screenshot still failed, no instagram_url — skipping %s", restaurant_name)
                        continue

                output_mp4 = tmp / f"{restaurant_name.replace(' ', '_')}_final.mp4"
                if not composite_video(spliced_mp4, screenshot, output_mp4):
                    log.warning("  [retry] FFmpeg composite failed — skipping %s", restaurant_name)
                    continue

                try:
                    drive_video_url, drive_thumbnail_url = upload_to_drive(
                        output_mp4, screenshot, restaurant_name, drive_folder_id
                    )
                except Exception as exc:
                    log.error("  [retry] Drive upload failed: %s", exc)
                    continue

                write_video_urls(ws, headers, i + 1, drive_video_url, drive_thumbnail_url)
                processed += 1
                screenshot.unlink(missing_ok=True)
                output_mp4.unlink(missing_ok=True)
                time.sleep(CRAWL_DELAY)

    log.info("Done. %d restaurant(s) processed.", processed)


# ── CLI ───────────────────────────────────────────────────────────────────────

def main():
    parser = argparse.ArgumentParser(description="ADVNC video generator")
    parser.add_argument("--limit", type=int, default=50, help="Max restaurants to process")
    parser.add_argument("--dry-run", action="store_true", help="Match only, no download/composite/upload")
    parser.add_argument("--restaurant", metavar="NAME", help="Process a single restaurant by name")
    parser.add_argument("--whoami", action="store_true", help="Test Loom auth — prints current user")
    args = parser.parse_args()

    if args.whoami:
        from dotenv import load_dotenv
        load_dotenv()
        loom = LoomClient(os.environ.get("LOOM_COOKIE", ""))
        result = loom.whoami()
        print("Loom auth response:", result)
        return

    if args.dry_run:
        log.info("DRY RUN — no files will be created or uploaded")

    run(limit=args.limit, dry_run=args.dry_run, only_restaurant=args.restaurant)


if __name__ == "__main__":
    main()
